
---
- name: Install Apache package
  yum:
    name: "{{ apache_pkg }}"
    state: present
  tags: install

- name: Copy custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache
  tags: config

- name: Start and enable Apache service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
  tags: service
